### PR TITLE
Refactor Code

### PR DESCRIPTION
**Pull request by aamir-asaram**
**In this milestone, I have implemented the following:**
- Relocated the farewell greeting after exiting the app to the end of the `main.rb` file
- Moved the `select person type` input to the `main.rb` file to maintain the `single-responsibility` principle - keeping all the "main menu" functionality in one file

_Also kindly note that as of this morning I am no longer paired with anyone for this group assignment as shown in the screenshot below_
Screenshot from 2023-09-04 12-13-33

### CODE REVIEW

**Comment by topeogunleye** [comment]
@aamir-asaram, Have you sent an email to student success to inform them of this?

image

**Comment by aamir-asaram** [comment]
@topeogunleye no, I didn't realise I had to. Thanks for letting me know! :smile:

**Comment by topeogunleye** [comment]
> @topeogunleye no, I didn't realise I had to. Thanks for letting me know! 😄

you're welcome 😄

**Comment by topeogunleye** [comment]
Hi @aamir-asaram, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ⚠️

   - You have submitted a pair programming project with no contributions from your partner.  Kindly report any issue you had with your partner to the `student success` team and they'll permit you to work solo or look for a suitable partner. Attach a screenshot of the message you received from `student success` stating that you can do the project alone in the pull request description and resubmit this PR👍

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

>Invalid Code Review Request **does not count** into the code reviews limit.

**Pull request merged**
